spring:
  datasource:
    username: webdav-ingester
    password: webdav-ingester
    url: jdbc:postgresql://localhost:5432/webdav-ingester
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

webdav:
  username: piotr
  password: Instrukcja10
  host: https://webdav.ptl.cloud/
  default:
    sync-storage-path: paperless-docs/

storage:
  base-dir: data/
  formats: pdf, epub

paperless:
  host: https://paperless.ptl.cloud
  password: instrukcja
  login: piotr
  default:
    tags:
      import-from-webdav: webdav
      import-from-paperless: sync
    correspondent: ingester
    document-type: ingester-default